### ISSUE TITLE
Spam in console with HolographicDisplays placeholder {time}.

### ISSUE THREAD

**Issue by s5gi** [SugarcaneMC/Sugarcane#21]
Hello, I'm experiencing an issue with the plugin HolographicDisplays, I'm running Sugarcane version git-Sugarcane-"7a5f1f6" (MC: 1.17), I am not sure whether or not this is a sugarcane issue or a Holographic Displays Issue. I'm sorry if it is HolographicDisplays and I have already made an issue post. The error I'm getting is linked below. This doesn't lower my expectations of sugarcane and I still plan to use it. I just wish for it to be fixed. Thanks!

`[22:18:49 WARN]: [HolographicDisplays] The placeholder {time} registered by the plugin HolographicDisplays generated an exception while updating. Please contact the author of HolographicDisplays java.lang.NullPointerException: Cannot invoke "java.text.SimpleDateFormat.format(java.util.Date)" because "com.gmail.filoghost.holographicdisplays.disk.Configuration.timeFormat" is null at com.gmail.filoghost.holographicdisplays.placeholder.PlaceholdersRegister.lambda$static$3(PlaceholdersRegister.java:50) ~[?:?] at com.gmail.filoghost.holographicdisplays.placeholder.Placeholder.update(Placeholder.java:78) ~[?:?] at com.gmail.filoghost.holographicdisplays.placeholder.PlaceholdersManager.lambda$load$0(PlaceholdersManager.java:66) ~[?:?] at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"] at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1556) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1259) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.jar:git-Sugarcane-"7a5f1f6"] at java.lang.Thread.run(Thread.java:831) [?:?]`

How to reproduce:

1. Goto https://github.com/SugarcaneMC/Sugarcane/actions/runs/972729848 and download the zip at the bottom of the screen.

2. Do the normal server jar startup procedure and place the plugin in the plugins folder.

3. Startup the server and create one or two holograms.

4. Startup the server and see the error.

(NOTE: The 3rd step is optional but the error occurred after I did step 3)

**Comment by Kylepoops** [comment]
`java.lang.NullPointerException: Cannot invoke "java.text.SimpleDateFormat.format(java.util.Date)" because "com.gmail.filoghost.holographicdisplays.disk.Configuration.timeFormat" is null`
Seems like a plugin issues but I'm not sure
But thanks you for reporting this

Can you reproduce it with our upstream Airplane?

**Comment by s5gi** [comment]
The error is still occurring with the upstream airplane build. Incase something has changed in the error, the error is linked below.

`
[14:59:50 WARN]: [HolographicDisplays] The placeholder {time} registered by the plugin HolographicDisplays generated an exception while updating. Please contact the author of HolographicDisplays
java.lang.NullPointerException: Cannot invoke "java.text.SimpleDateFormat.format(java.util.Date)" because "com.gmail.filoghost.holographicdisplays.disk.Configuration.timeFormat" is null
        at com.gmail.filoghost.holographicdisplays.placeholder.PlaceholdersRegister.lambda$static$3(PlaceholdersRegister.java:50) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.placeholder.Placeholder.update(Placeholder.java:78) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.placeholder.PlaceholdersManager.lambda$load$0(PlaceholdersManager.java:66) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Sugarcane-"c5a1c8b"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Sugarcane-"c5a1c8b"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1556) ~[patched_1.17.jar:git-Sugarcane-"c5a1c8b"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[patched_1.17.jar:git-Sugarcane-"c5a1c8b"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[patched_1.17.jar:git-Sugarcane-"c5a1c8b"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1259) ~[patched_1.17.jar:git-Sugarcane-"c5a1c8b"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.jar:git-Sugarcane-"c5a1c8b"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
`

**Comment by Kylepoops** [comment]
Seems like the same error, it should be a plugin's bug.
So please contact the plugin author
Also you can try it with Paper and Tuinity if you wanna confirm

**Comment by Kylepoops** [comment]
Closed because have nothing to do with Sugarcane
